# Application configuration
[app]
# Debug level
level = "info"

[server]
port = 8844
# bind = "127.0.0.1"

[server.database]
# Only sqlite3 is supported as database.
Sqlite = "config/db.sqlite3"

# Uncomment to start the telegram bot
# [telegram]
# token = ""
# server = ""

username = ""
password = ""
